'use client'

import { useEffect, useState } from 'react'
import { getMyOffers, deleteOffer, Offer } from '@/lib/firebase/firestore'
import { onAuth, signInWithGoogle } from '@/lib/firebase/auth'
import { statusColor, statusLabel } from '@/lib/utils/validation'
import OfferForm from '@/components/offers/OfferForm'
import { Plus, Pencil, Trash2, ListChecks, Loader2, LogIn } from 'lucide-react'
import toast from 'react-hot-toast'
import clsx from 'clsx'
import { User } from 'firebase/auth'

export default function MyOffersPage() {
  const [offers,    setOffers]    = useState<Offer[]>([])
    const [loading,   setLoading]   = useState(true)
      const [user,      setUser]      = useState<User | null | undefined>(undefined)
        const [showForm,  setShowForm]  = useState(false)
          const [editing,   setEditing]   = useState<Offer | null>(null)
            const [deleting,  setDeleting]  = useState<string | null>(null)
              const [signingIn, setSigningIn] = useState(false)
              
                async function load(uid: string) {
                    setLoading(true)
                        const data = await getMyOffers(uid)
                            setOffers(data)
                                setLoading(false)
                                  }
                                  
                                    useEffect(() => {
                                        return onAuth((u) => {
                                              setUser(u)
                                                    if (u) load(u.uid)
                                                          else   setLoading(false)
                                                              })
                                                                }, [])
                                                                
                                                                  async function handleSignIn() {
                                                                      setSigningIn(true)
                                                                          try { await signInWithGoogle() }
                                                                              catch (e: any) {
                                                                                    if (e?.code !== 'auth/popup-closed-by-user') toast.error('فشل تسجيل الدخول')
                                                                                        } finally { setSigningIn(false) }
                                                                                          }
                                                                                          
                                                                                            async function handleDelete(offer: Offer) {
                                                                                                if (!confirm('هل أنت متأكد من حذف هذا العرض؟')) return
                                                                                                    setDeleting(offer.id!)
                                                                                                        try {
                                                                                                              await deleteOffer(offer.id!)
                                                                                                                    toast.success('تم حذف العرض')
                                                                                                                          if (user) load(user.uid)
                                                                                                                              } catch {
                                                                                                                                    toast.error('حدث خطأ أثناء الحذف')
                                                                                                                                        } finally { setDeleting(null) }
                                                                                                                                          }
                                                                                                                                          
                                                                                                                                            function handleFormClose() {
                                                                                                                                                setShowForm(false)
                                                                                                                                                    setEditing(null)
                                                                                                                                                        if (user) load(user.uid)
                                                                                                                                                          }
                                                                                                                                                          
                                                                                                                                                            if (user === undefined) {
                                                                                                                                                                return <div className="flex justify-center py-24"><div className="animate-spin rounded-full h-10 w-10 border-4 border-[#2E86AB] border-t-transparent" /></div>
                                                                                                                                                                  }
                                                                                                                                                                  
                                                                                                                                                                    if (!user) {
                                                                                                                                                                        return (
                                                                                                                                                                              <div className="flex flex-col items-center justify-center py-24 gap-5">
                                                                                                                                                                                      <ListChecks className="w-16 h-16 text-gray-300" />
                                                                                                                                                                                              <div className="text-center">
                                                                                                                                                                                                        <p className="text-lg font-semibold text-gray-700 mb-1">تسجيل الدخول مطلوب</p>
                                                                                                                                                                                                                  <p className="text-sm text-gray-400">سجّل دخولك بـ Google لإدارة عروضك</p>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                  <button onClick={handleSignIn} disabled={signingIn}
                                                                                                                                                                                                                                            className="flex items-center gap-2 bg-[#1B3A6B] text-white px-6 py-3 rounded-xl text-sm font-semibold disabled:opacity-60 min-h-[48px]">
                                                                                                                                                                                                                                                      <LogIn className="w-4 h-4" />
                                                                                                                                                                                                                                                                {signingIn ? 'جارٍ تسجيل الدخول…' : 'دخول بـ Google'}
                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                <div className="flex items-center justify-between mb-4">
                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                  <h1 className="text-xl sm:text-2xl font-bold text-[#1B3A6B]">عروضي</h1>
                                                                                                                                                                                                                                                                                                                            <p className="text-gray-500 text-sm mt-0.5">{offers.length} عرض</p>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                            <button onClick={() => { setEditing(null); setShowForm(true) }}
                                                                                                                                                                                                                                                                                                                                                      className="flex items-center gap-2 bg-[#1B3A6B] text-white px-4 py-2.5 rounded-xl text-sm font-semibold active:bg-[#142D52] transition-colors min-h-[44px]">
                                                                                                                                                                                                                                                                                                                                                                <Plus className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                          <span className="hidden sm:inline">إنشاء عرض جديد</span>
                                                                                                                                                                                                                                                                                                                                                                                    <span className="sm:hidden">عرض جديد</span>
                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-center py-24"><div className="animate-spin rounded-full h-10 w-10 border-4 border-[#2E86AB] border-t-transparent" /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                      ) : offers.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-center py-24 text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <ListChecks className="w-14 h-14 mx-auto mb-4 opacity-30" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-base mb-4">لم تنشئ أي عروض بعد</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => setShowForm(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-[#1B3A6B] text-white px-6 py-3 rounded-xl text-sm font-semibold active:bg-[#142D52] transition-colors min-h-[48px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    إنشاء أول عرض
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {offers.map(offer => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={offer.id} className="bg-white rounded-2xl border border-gray-100 p-4 sm:p-5 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-start justify-between gap-2 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex flex-wrap items-center gap-2 min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className={clsx('text-xs font-medium px-2.5 py-1 rounded-full whitespace-nowrap', statusColor(offer.status))}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {statusLabel(offer.status)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-sm text-gray-500 truncate">{offer.ownerStation}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-xs text-gray-400">{offer.offerMonth}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {offer.status !== 'confirmed' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-1 flex-shrink-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => { setEditing(offer); setShowForm(true) }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="p-2.5 text-gray-400 active:text-[#2E86AB] active:bg-blue-50 rounded-xl transition-colors min-w-[40px] min-h-[40px] flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Pencil className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {offer.status !== 'selected' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => handleDelete(offer)} disabled={deleting === offer.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="p-2.5 text-gray-400 active:text-red-500 active:bg-red-50 rounded-xl transition-colors disabled:opacity-50 min-w-[40px] min-h-[40px] flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {deleting === offer.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <Trash2 className="w-4 h-4" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs text-gray-400 mb-1.5">أيام الطلب</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-wrap gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {offer.daysOff.map((d, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span key={i} className="text-xs bg-red-50 text-red-700 border border-red-100 px-2 py-1 rounded-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {d.date} · {({ day:'صباحي', night:'مسائي', overlap:'تداخل' } as Record<string,string>)[d.shift]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {offer.selectorName && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-3 p-3 bg-orange-50 border border-orange-100 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs text-orange-700 font-medium">اختاره: {offer.selectorName} — {offer.selectorStation}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-400 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {offer.createdAt ? ((d: Date) => `${d.getDate()} ${['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'][d.getMonth()]} ${d.getFullYear()}`)((offer.createdAt as any).toDate()) : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {showForm && <OfferForm uid={user.uid} displayName={user.displayName} offer={editing} onClose={handleFormClose} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      '